SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `nominatim` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `nominatim`;

DROP TABLE IF EXISTS `bounding_boxes`;
CREATE TABLE IF NOT EXISTS `bounding_boxes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_roads_data` int(11) NOT NULL,
  `southLatitude` double NOT NULL,
  `northLatitude` double NOT NULL,
  `westLongitude` double NOT NULL,
  `eastLongitude` double NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `roads_data`;
CREATE TABLE IF NOT EXISTS `roads_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `road` text NOT NULL,
  `suburb` text NOT NULL,
  `city` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
